
### vertx products
GET http://127.0.0.1:18001/products

### vertx -> spring -> users
GET http://127.0.0.1:18001/users

### spring -> list
GET http://127.0.0.1:10001/user/list

### spring -> vertx -> products
GET http://127.0.0.1:10001/user/products

####################################################3
####################################################3
########### gateway 
####################################################3
####################################################3

### vertx products
GET http://127.0.0.1:10000/products/products

### vertx -> spring -> users
GET http://127.0.0.1:10000/products/users

### spring -> list
GET http://127.0.0.1:10000/users/user/list

### spring -> vertx -> products
GET http://127.0.0.1:10000/users/user/products

### 清除consul 服务
PUT http://127.0.0.1:8500/v1/agent/service/deregister/serviceId18001